name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - develop
  push: 
    branches: [ feature/check ]

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    env:
      ENVIRONMENT: dev

    steps:
      - name: Set lowercase and uppercase env vars
        id: env-setup
        run: |
          # Lowercase (from input)
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV

          # Uppercase (for GitHub vars like DEV_SCRIPTS_PATH)
          UPPER_ENV=$(echo "${{ env.ENVIRONMENT }}" | awk '{print toupper($0)}')
          # UPPER_ENV=$(echo "$ENVIRONMENT" | tr '[:lower:]' '[:upper:]')
          echo "ENV_UPPER=$UPPER_ENV" >> $GITHUB_ENV

          # Now manually map repo vars
          case "$UPPER_ENV" in
            DEV)
              echo "SCRIPTS_PATH=${{ vars.DEV_SCRIPTS_PATH }}" >> $GITHUB_ENV
              echo "SERVER_IP=${{ vars.DEV_SERVER_IP }}" >> $GITHUB_ENV
              ;;
            PROD)
              echo "SCRIPTS_PATH=${{ vars.PROD_SCRIPTS_PATH }}" >> $GITHUB_ENV
              echo "SERVER_IP=${{ vars.PROD_SERVER_IP }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unsupported environment: $UPPER_ENV"
              exit 1
              ;;
          esac

      - name: Show resolved variables
        run: |
          echo "ENVIRONMENT (lower): $ENVIRONMENT"
          echo "ENVIRONMENT (upper): $ENV_UPPER"
          echo "SCRIPTS_PATH: $SCRIPTS_PATH"
          echo "SERVER_IP: $SERVER_IP"          

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Check outputs
      run: |
        echo "output: ${{ steps.vars.outputs.sha_short }}"
        echo "short: $sha_short"

    - name: Bump version for master
      if: github.base_ref == 'master'
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        PRERELEASE: false

    - name: Bump version for develop (pre-release)
      if: github.base_ref == 'develop'
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        PRERELEASE: true
        PRERELEASE_SUFFIX: pre
